import { colors } from '../../styles/colors';
import { typography } from '../../styles/typography/typography';

export const buttonStyles = {
  primary: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '143px',
    border: 'none',
    color: colors.NeutralWhite,
    borderRadius: typography.border.radius,
    paddingLeft: typography.size.large,
    paddingRight: typography.size.large,
    fontWeight: typography.weight.bold,
    cursor: 'pointer',
  },
  secondary: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '143px',
    border: `${typography.border.width} solid ${colors.Accessory1}`,
    backgroundColor: colors.NeutralWhite,
    color: colors.Accessory1,
    borderRadius: typography.border.radius,
    paddingLeft: typography.size.large,
    paddingRight: typography.size.large,
    fontWeight: typography.weight.regular,
    cursor: 'pointer',
  },
  cta: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '143px',
    border: 'none',
    backgroundColor: colors.CTA,
    color: colors.NeutralWhite,
    borderRadius: typography.border.radius,
    paddingLeft: typography.size.large,
    paddingRight: typography.size.large,
    fontWeight: typography.weight.bold,
    cursor: 'pointer',
  },
};
